name: Server CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  server-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "server/.nvmrc"
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: ./server
        run: pnpm install

      - name: Run tests
        working-directory: ./server
        run: pnpm test:run

      - name: Type checking
        working-directory: ./server
        run: pnpm type-check

      - name: Lint and format
        working-directory: ./server
        run: |
          pnpm lint:fix
          pnpm format
          pnpm lint  # Verify fixes
          pnpm format:check

      - name: Test coverage
        working-directory: ./server
        run: pnpm coverage